language: node_js
node_js:
- '0.10'
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
env:
  global:
  - secure: dtiDjGKC55oA3x84+/QZG1tJiDzTXQ0xW4kNnvk8P3hl4zpDVDdZZmKP1tlfp+6H9msp97ee/7oUlwOZE2V3zdXly3lg507DAf4ab4em6cxMtDyhgIUCyw8tJJVMvwIwO4NA7jJMfxgfp3DMABLSI35nQBAINL4vynV3H4vi1bU=
  - secure: rX2bmEL2aTroTpZtBnwcdYj21xUlQUPWVY2BC7pDu2rWD75exRUwLPUpgY1cX6ADJGyjs+5+1voKBKsARsDX6yWG3KlVFS71OFWao7Tab9DMG8Yt6K29u0v/ETvTnHztlX92HXXODxh9jH2XZ0UBBq2JGMvXLUCcBLkLhyxbd4c=
